version: '2'
services:
  zookeeper:
    image: zookeeper:3.4.9
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    links:
      - zookeeper:zk
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_ADVERTISED_HOST_NAME: localhost
  auth:
    image: esolutionsacademy/auth-florin
    ports:
      - "9999:9999"

  inventory:
    image: esolutionsacademy/inventory-florin
    links:
      - discovery:discovery
      - kafka:kafka
      - zookeeper:zookeeper
    environment:
      DISCOVERY: discovery
      KAFKA: kafka
      ZOOKEEPER: zookeeper

  store:
    image: esolutionsacademy/store-florin
    ports:
      - "8081:8081"
    links:
      - discovery:discovery
      - kafka:kafka
      - zookeeper:zookeeper
    environment:
      DISCOVERY: discovery
      KAFKA: kafka
      ZOOKEEPER: zookeeper

  discovery:
    image: esolutionsacademy/discovery-florin
    ports:
      - "8761:8761"

  gateway:
    image: esolutionsacademy/gateway-florin
    ports:
      - "8080:8080"
    links:
      - discovery:discovery
    environment:
      DISCOVERY: discovery
